### ISSUE TITLE
Search error message

### ISSUE THREAD

**Issue by dvvvsh** [PawelGorny/WifSolver#8]
MacBook-Air-3 wifsolver-master % java -jar wifsolver.jar search.conf
Exception in thread "main" java.lang.IllegalArgumentException: No enum constant com.pawelgorny.wifsolver.WORK.Search
	at java.base/java.lang.Enum.valueOf(Enum.java:273)
	at com.pawelgorny.wifsolver.WORK.valueOf(WORK.java:3)
	at com.pawelgorny.wifsolver.Main.readConfiguration(Main.java:139)
	at com.pawelgorny.wifsolver.Main.main(Main.java:20)

**Comment by PawelGorny** [comment]
Are you sure your configuration file is correct?

**Comment by tanveer7562** [comment]
Hello sir help me how to use WIFSolver Tool  in Kali Linux please help me 🙏🙏🙏🙏
